[build]
  command = "cd smarter-tasks && npm ci && npm run build"
  functions = "netlify/functions"
  publish = "smarter-tasks/dist"

  # Redirect for Single Page Applications
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build.environment]
  NODE_VERSION = "18"
